export const DEV_DEPENDENCIES: Record<string, string> = {
  '@biomejs/biome': '^2.4.8',
  '@commitlint/cli': '^20.5.0',
  '@commitlint/config-conventional': '^20.5.0',
  '@tsconfig/node22': '^22.0.5',
  '@types/node': '^25.5.0',
  '@vitest/coverage-v8': '^4.1.0',
  bonvoy: '^0.13.1',
  concurrently: '^9.2.1',
  lefthook: '^2.1.4',
  'lockfile-lint': '^5.0.0',
  'ls-engines': '^0.10.0',
  'npm-package-json-lint': '^9.1.0',
  rimraf: '^6.1.3',
  'sort-package-json': '^3.6.1',
  tsdown: '^0.21.4',
  typescript: '^5.9.3',
  vitest: '^4.1.0',
};

export const SCRIPTS: Record<string, string> = {
  build: 'tsdown',
  clean: 'rimraf dist',
  lint: 'concurrently npm:lint:* --prefixColors auto',
  'lint:engines': 'ls-engines',
  'lint:format': 'biome check --write',
  'lint:lockfile': 'lockfile-lint',
  'lint:package': 'npmPkgJsonLint .',
  'lint:sort_package': 'sort-package-json "package.json"',
  'lint:typecheck': 'tsc --noEmit',
  prepare: '[ "$CI" = \'true\' ] || lefthook install',
  test: 'vitest run',
  'test:coverage': 'vitest run --coverage',
};
